# -*- coding: utf-8 -*-
"""rag_implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUxE1DWFWkL2F1t5BY_V4Ktj4r1MZvY_
"""

"""
Install the required libraries
!pip install langchain langchain-google-genai langchain faiss-cpu langchain-text-splitters langchain-community
"""
import os
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import PromptTemplate

os.environ["GEMINI_API_KEY"] = "ADD_GEMINI_API_KEY_HERE"

text ="""ADD_YOUR_KNOWLEDGE_BASE_TEXT_HERE"""

splitter = RecursiveCharacterTextSplitter(chunk_size = 200, chunk_overlap =50)

docs = splitter.create_documents([text])

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

vectorstore = FAISS.from_documents(docs,embeddings)

retrieve = vectorstore.as_retriever(search_kwargs = {"k" : 3})

def format_docs(docs):
  return "\n\n".join(d.page_content for d in docs)

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""

    Use only the context below to answer the question.

    context:
    {context}

    question:
    {question}

    Answer:
    """
)

llm = ChatGoogleGenerativeAI(model = "gemini-2.5-flash")

def rag_answer(query):
  r_docs = retrieve.invoke(query)
  context = format_docs(r_docs)
  full_prompt = prompt.format(context = context, question = query)
  response = llm.invoke(full_prompt)

  return response.content

query = "What is python used for?"
answer =rag_answer(query)

print("question: ", query)
print("\n")
print("answer", answer)